# Generated by Django 3.2.9 on 2022-01-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('1', '09:00'), ('2', '09:15'), ('3', '09:30'), ('4', '09:45'), ('5', '10:00'), ('6', '10:15'), ('7', '10:30'), ('8', '10:45'), ('9', '11:00'), ('10', '11:15'), ('11', '11:30'), ('12', '11:45'), ('13', '12:00'), ('14', '12:15'), ('15', '12:30'), ('16', '12:45'), ('17', '13:00'), ('18', '13:15'), ('19', '13:30'), ('20', '13:45'), ('21', '14:00'), ('22', '14:15'), ('23', '14:30'), ('24', '14:45'), ('25', '15:00'), ('26', '15:15'), ('27', '15:30'), ('28', '15:45'), ('29', '16:00'), ('30', '16:15'), ('31', '16:30'), ('32', '16:45'), ('33', '17:00'), ('34', '17:15'), ('34', '17:30'), ('35', '17:45'), ('36', '18:00')], max_length=200),
        ),
    ]
