# Generated by Django 3.2.9 on 2021-12-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKING_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Booking',
        ),
    ]
