# Generated by Django 3.2.9 on 2021-12-19 15:37

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKING_APP', '0002_rename_item_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
